; Escribir un programa que dado un string llamado MENSAJE, almacenado en la
; memoria de datos, cuente la cantidad de veces que la letra ‘a’ (minúscula) aparece en MENSAJE y lo
; almacene en la variable CANT. Por ejemplo, si MENSAJE contiene “Hola, Buenas Tardes”, entonces
; CANT debe valer 3.

org 1000h
MENSAJE DB "Hola , buenas tardes"
FIN_PALABRA DB ?

ORG 2000H
MOV AX, OFFSET FIN_PALABRA - OFFSET MENSAJE ; CUENTO LA CANTIDAD DE CARATERES DE LA ORACION
MOV CL, 0 ;  SET CL EN O, LO USO PARA CONTAR LAS "a"
MOV BX, OFFSET MENSAJE ; VOY AL INICIO DE LA ORACION
BUCLE: CMP BYTE PTR[BX], 61H ; COMPARO LETRA ACTUAL
JNZ NOESA ; LA LETRA COMPARADA NO ES A
JMP ESA ; LA LETRA COMPARADA SI ES A

NOESA: INC BX ; PASO A LA SIGUIENTE LETRA
DEC AX ; BAJO EL CONTADOR DE CARACTERES RESTANTES
JZ FIN ; SI NO QUEDAN CARACTERES, SALTO AL FINAL DEL PROGRAMA
JMP BUCLE ; SI SI QUEDAN CARACTERES, VUELVO AL BUCLE

ESA: INC CL ; AUMENTO EL CONTADOR DE LETRAS "a" ENCONTRADAS
INC BX ; PASO A LA SIGUIENTE LETRA
DEC AX ; BAJO EL CONTADOR DE CARACTERES RESTANTES
JZ FIN ; SI NO QUEDAN CARACTERES, SALTO AL FINAL DEL PROGRAMA
JMP BUCLE ; SI SI QUEDAN CARACTERES, VUELVO AL BUCLE

FIN: hlt ; FINAL DEL PROGRAMA
end
