ORG 1000H
MSJ DB "ARQUITECTURA DE COMPUTADORAS-"
    DB "FACULTAD DE INFORMATICA-"
    DB 55H
    DB 4EH
    DB 4CH
    DB 50H
FIN DB ?

ORG 2000H
MOV BX, OFFSET MSJ
MOV AL, OFFSET FIN - OFFSET MSJ
INT 7
INT 0
END

; a) Ejecutar en el simulador ¿qué imprime? Imprime ARQUITECTURA DE COMPUTADORAS - FACULTAD DE INFORMATICA - UNLP
;b) ¿Por qué imprime “UNLP” al final? PORQUE IMPRIME LOS VALORES ASCII DE 55H, 4EH, 4CH, 50H
;c) Con referencia a la interrupción INT 7, ¿qué se almacena en los registros BX y AL?
; EN EL REGISTRO BX SE GUARDA LA DIRECCION DONDE INICIA EL MENSAJE A IMPRIMIR
; EN EL REGISTRO AL SE GUARDA LA CANTIDAD DE CARACTERES QUE TIENE EL MENSAJE
